apiVersion: apps/v1
kind: Deployment
metadata:
  name: gym-app-deployment
  namespace: gym-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gym-app
  template:
    metadata:
      labels:
        app: gym-app
    spec:
      containers:
        - name: gym-app
          image: aboelaiz/gym:latest
          ports:
            - containerPort: 3001
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          envFrom:
            - configMapRef:
                name: gym-config
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3001"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gym-secrets
                  key: postgres-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gym-secrets
                  key: jwt-secret
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gym-secrets
                  key: email-password
---
apiVersion: v1
kind: Service
metadata:
  name: gym-app-service
  namespace: gym-app
spec:
  selector:
    app: gym-app
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
