apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gym-ingress
  namespace: gym-app
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - gym.local
    secretName: gym-tls-secret
  rules:
  - host: gym.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gym-app-service
            port:
              number: 3001
